config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'users#dashboard'
  get 'job_show', to: 'users#job_show'
  post 'job_update_test', to: 'users#job_update_test'
  get 'skill_show', to: 'users#skill_show'
  # get 'professional_update', to: 'users#professional_update'
  #  post 'job_update', to: 'users#job_update' fais la nouvelle ne sert plus
  post 'skill_update', to: 'users#skill_update'
  get 'profile', to: 'users#profile'
  get 'dashboard', to: 'users#dashboard'
  patch 'update_users', to: 'users#update_users'
  patch 'description_maj', to: 'users#description_maj'
  get 'matches', to: "offers#matches"
  get 'dashboard', to: 'users#dashboard', as: :user_root
  get 'message_index', to: 'users#message_index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :matches, only: %i[show]
  resources :users, only: %i[show]
  resources :chatrooms, only: :show do
    resources :messages, only: :create
  end

  resources :offers, only: %i[index show] do
    post 'like', to: 'matches#like'
    post 'reject', to: 'matches#reject'
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :messages
  has_many :user_jobs
  has_many :jobs, through: :user_jobs
  has_many :user_skills
  has_many :skills, through: :user_skills
  has_many :offers, dependent: :destroy
  has_many :matches
  has_one_attached :photo
  # pour les choix dans les form
  RECRUTOR = { oui: true, non: false }
  GENDER = ['homme', 'femme']
  ##
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :timeoutable
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  ################################# USER ################################
  def profile
    @user = current_user
    @profile_user = User.find(params[:format])
  end

  def sign_out
  end

  def update_users
    @user = current_user
    @user.update(user_params)
    redirect_to profile_path(@user)
  end

  # Update of the description of the current_user

  def description_maj
    @user = current_user
    @description = params[:user][:description]
    @user.description = @description
    @user.save!
    redirect_to professional_update_path
  end

  ########################################################################################
  def dashboard
    @user = current_user
  end

  def message_index
    @chatrooms = Chatroom.where(user_id: current_user) + Chatroom.where(recrutor: current_user)
  end

  def job_show
    @job_user = UserJob.where(user_id: current_user.id)
    @job = UserJob.new
    @jobs = Job.order(name: :asc)
    @jobs = @jobs.where('name ILIKE ?', "%#{params[:query]}%") if params[:query].present?

    respond_to do |format|
      format.html # Follow regular flow of Rails
      format.text { render partial: 'users/list_jobs', locals: { jobs: @jobs }, formats: [:html] }
    end
  end

  def job_update_test
    @user = current_user
    @experience = params[:user_job][:experience].to_i
    @idjob = params[:job_id].split[1].to_i
    if @user.jobs.ids.include?(@idjob)
      @user_job = UserJob.where(job_id: @idjob)
      @user_job.update(experience: @experience)
    else
      @user_job = UserJob.new(experience: @experience, job_id: @idjob)
      @user_job.user = @user
      @user_job.save
    end
    redirect_to job_show_path
  end

  def skill_show
    @job_skill = UserSkill.where(user_id: current_user.id)
    @skill = UserSkill.new
    @skills = Skill.order(name: :asc)
    @skills = @skills.where('name ILIKE ?', "%#{params[:query]}%") if params[:query].present?

    respond_to do |format|
      format.html
      format.text { render partial: 'users/list_skills', locals: { skills: @skills }, formats: [:html] }
    end
  end

  def skill_update
    @user = current_user
    @level = params[:user_skill][:level]
    @idskill = params[:skill_id].split[1].to_i
    if @user.skills.ids.include?(@idskill)
      @user_skill = UserSkill.where(skill_id: @idskill)
      @user_skill.update(level: @level)
    else
      @user_skill = UserSkill.new(level: @level, skill_id: @idskill)
      @user_skill.user = @user
      @user_skill.save
    end
    redirect_to skill_show_path
  end

  private

  ####################### PARAMS_USER_SKILLS #########################################
  def params_user_skills
    params.require(:user_skill).permit(:level, :skill_id)
  end

  ########################################################################################

  ####################### PARAMS_USER_JOBS #########################################

  def params_user_jobs
    params.require(:user_job).permit(:experience, :job_id)
  end

  ##################################################################################
  def user_params
    params.require(:user).permit(:email, :password, :first_name, :last_name, :city, :gender, :birthdate, :recrutor,
                                 :description, :photo)
  end

  ########################################################################################
end

app/views/users/_list_jobs.html.erb
<div data-hello-target="liste">
  <% if params[:query].blank? %>
    <div class="b-margin-20"></div>
    <h4>Choisir un métier</h4>
    <div class="b-margin-20"></div>
  <% else %>
    <h5><%= pluralize @jobs.count, 'resultats' %> pour <code><%= params[:query] %> </code></h5>
  <% end %>
  <% @jobs.each do |job| %>
    <%= simple_form_for @job, url: job_update_test_path, method: :post do |f| %>
      <%= f.label job.name, class: @job_user.find_by_job_id(job.id) ? "d-none" : "job-name info-pill pill-obsydian ", data: {job: job.id} %>
      <div class="job-form-<%= job.id %> d-none">
        <div class= form-job-content>
          <%= f.input :experience, placeholder: "Votre experience en mois" %>
          <%= hidden_field_tag :job_id, value: job.id %>
          <%= f.submit "Ajouter" %>
        </div>
      </div>
    <% end %>
  <% end %>
</div>

app/views/users/_list_skills.html.erb
<div data-hello-target="liste">
  <% if params[:query].blank? %>
    <div class="b-margin-20"></div>
    <h4>Choisir mes compétences</h4>
    <div class="b-margin-20"></div>
  <% else %>
    <h5><%= pluralize @skills.count, 'resultats' %> pour <code><%= params[:query] %> </code></h5>
  <% end %>
  <% @skills.each do |skill| %>
    <%= simple_form_for @skill, url: skill_update_path, method: :post do |f| %>
      <%= f.label skill.name, class: @job_skill.find_by_skill_id(skill.id) ? "d-none" : "skill-name info-pill pill-obsydian", data: {skill: skill.id} %>
      <div class="skill-form-<%= skill.id %> d-none">
        <div class= form-job-content>
          <%= f.input :level, label: "Votre niveau sur 5", collection: UserSkill::LEVEL %>
          <%= hidden_field_tag :skill_id, value: skill.id %>
          <%= f.submit "Ajouter" %>
        </div>
      </div>
    <% end %>
  <% end %>
</div>

app/views/users/dashboard.html.erb
<div class="content dashboard">
  <%= render "shared/usercard"%>
  <div class="b-margin-40"></div>
  <%= link_to profile_path(@user), class: "dashboard-pill dash-grey" do%>
    <h4>👤</h4>
    <p>Mes informations</p>
    <p class="fas fa-chevron-right"></p>
  <% end %>
  <div class="b-margin-20"></div>
  <%= link_to job_show_path, class: "dashboard-pill dash-grey" do%>
    <h4>💼</h4>
    <p>Profil professionnel</p>
    <p class="fas fa-chevron-right"></p>
  <% end %>
  <div class="b-margin-20"></div>
  <%= link_to skill_show_path, class: "dashboard-pill dash-grey" do%>
    <h4>💪</h4>
    <p>Mes compétences</p>
    <p class="fas fa-chevron-right"></p>
  <% end %>
  <div class="b-margin-20"></div>
  <%= link_to edit_user_registration_path, class: "dashboard-pill dash-grey" do%>
    <h4>🔐</h4>
    <p>Paramètres de compte</p>
    <p class="fas fa-chevron-right"></p>
  <% end %>
  <div class="b-margin-40"></div>
  <%= link_to matches_path, class: "dashboard-pill dash-jaune" do%>
    <h4>🔍</h4>
    <p>Voir mes matchs</p>
    <p class="fas fa-chevron-right"></p>
  <% end %>
  <div class="b-margin-40"></div>
</div>

app/views/users/job_show.html.erb
<%= render "/shared/dashboardnavigationbar", pathname: "Profil professionnel "%>
<div class="content-long-dashboard dashboard text-center">
  <div class="b-margin-30"></div>
  <% if @job_user.count.positive? %>
    <h4>Mes métiers</h4>
    <div class="b-margin-20"></div>
    <% @job_user.each do |job| %>
      <p class="dashboard-pill pill-lavande d-flex justify-content-center choosen-job" data-job="<%= job.job_id %>"><%= Job.find(job.job_id).name %> : <%= UserJob.find_by_job_id(job.job_id).experience %> mois</p>
      <%= simple_form_for @job, url: job_update_test_path, method: :post do |f| %>
        <div class="choosen-job-form-<%= job.job_id %> d-none">
          <div class= form-job-content>
            <%= f.input :experience, placeholder: "Votre experience en mois" %>
            <%= hidden_field_tag :job_id, value: job.job_id %>
            <%= f.submit "Modifier" %>
          </div>
        </div>
      <% end %>
    <% end %>
  <% end %>
  <div data-controller="hello" class="relative-content-searchbar">
    <%= form_with url: job_show_path, method: :get, html: {
   data: { hello_target: 'formulaire' } } do |f| %>
      <span class="input-search-div">
        <%= f.text_field :query,
                     class: "form-control",
                     placeholder: 'chercher un métier',
                     value: params[:query],
                     data: { hello_target: 'button', action: 'keyup->hello#update' } %>
      <% end %>
    </span>
    <%= render "list_jobs", jobs: @jobs %>
    <div class="b-margin-40"></div>
  </div>
</div>

app/views/users/message_index.html.erb
<div class="content-long dashboard">
  <% if @chatrooms.count.positive? %>
    <% @chatrooms.each do |chatroom| %>
      <% if chatroom.user_id == current_user.id %>
        <% prenom = User.find(chatroom.recrutor).first_name %>
        <% nom = User.find(chatroom.recrutor).last_name %>
        <% patronyme = "#{prenom} #{nom}"%>
      <% else %>
        <% prenom = User.find(chatroom.user_id).first_name %>
        <% nom = User.find(chatroom.user_id).last_name %>
        <% patronyme = "#{prenom} #{nom}"%>
      <% end %>
      <% if  chatroom.messages.last && chatroom.messages.last.user_id == current_user.id %>
        <% css_class = 'pill-obsydian'%> <% else %> <% css_class = 'pill-lavande'%> <% end %>
      <%= link_to chatroom_path(chatroom), id: 'relative-notif' do%>
        <div class="message-card <%=css_class%>">
          <% if chatroom.messages %>
            <% chatroom.messages.each do |message|%>
              <% unless message.user_id == current_user.id %>
                <% if message.status == false %>
                  <div class="index-message-notif"></div>
                <% end %>
              <% end %>
            <% end %>
          <% end %>
          <%= render 'shared/avatar_recrutor', chatroom: chatroom, imageurl: "cl_image_path chatroom.offer.photo.key, width: 50, height: 50" %>
          <div class="max-lenght">
            <h4><%=patronyme.titleize%></h4>
            <h6><%= Offer.where(user_id: chatroom.recrutor).first.company_name %></h6>
            <p><%=chatroom.name.capitalize%></p>
          </div>
        </div>
      <% end %>
    <% end %>
  <% else %>
    <div class="nothingfound">
      <span class="d-flex justify-content-center" style="font-size: 100px;">😭</span>
      <h5 style="text-align: center;">Personne ne<br>
        vous a encore<br>
        écrit...</h5>
    </div>
  <% end %>
</div>

app/views/users/new_user_jobs.html.erb
<%= simple_form_for @user_job, url: create_user_jobs_users_path do |f| %>
  <%= f.input :experience, collection: UserJob::EXPERIENCE %>
  <%= f.input :job_id, as: :check_boxes, collection: Job.all, wrapper: :vertical_collection_inline %>
  <%= f.submit %>
<% end %>

app/views/users/new_user_skills.html.erb
<%= simple_form_for @user_skill, url: create_user_skills_users_path do |f| %>
  <%= f.input :level, collection: UserSkill::LEVEL %>
  <%= f.input :skill_id, as: :check_boxes, collection: Skill.all, wrapper: :vertical_collection_inline %>
  <%= f.submit %>
<% end %>

app/views/users/professional_update.html.erb
<%= render '/shared/navigationbar', pathname: 'Mes informations'%>
<div class="content-long-dashboard dashboard">
  <div class="b-margin-40"></div>
  <button class="job-button button-pill-large"> Ajouter un emploi </button>
  <div class="b-margin-40"></div>
  <div class="job-list d-none">
    <% Job.all.each do |job| %>
      <%= simple_form_for @job, url: job_update_path do |f| %>
        <%= f.label job.name %>
        <%= f.input :experience %>
        <%= hidden_field_tag :job_id, value: job.id %>
        <%= f.submit %>
      <% end %>
    <% end %>
  </div>
  <%= simple_form_for @skill, url: skill_update_path do |f| %>
    <%= f.association :skill, input_html: { multiple: true } %>
    <%= f.input :level, collection: UserSkill::LEVEL %>
    <%= f.submit %>
  <% end %>
  <%= simple_form_for @user, url: description_maj_path(@user) do |f| %>
    <%= f.text_area :description, :cols => 40, :rows => 6 %>
    <div class="b-margin-40"></div>
    <%= f.submit %>
    <div class="b-margin-40"></div>
  <% end %>
</div>

app/views/users/profile.html.erb
<%# Condition to verify if the user is on is own profile and can access to the change %>
<% if @user == @profile_user %>
  <%= render '/shared/dashboardnavigationbar', pathname: 'Mes informations'%>
  <div class="content-long-dashboard dashboard pr-3 pl-3">
    <!-- !!!! Attention, don't modify the existing class for JS !!!!!
    This div is here to display the user infos-->
    <div class="user-info">
      <div class="b-margin-20"></div>
      <div class="d-flex justify-content-center">
        <%= render '/shared/avatar' %>
      </div>
      <div class="b-margin-20"></div>
      <p class="dashboard-info-pill dash-grey"><b>👤 Nom : </b><%= @user.last_name %></p>
      <div class="b-margin-20"></div>
      <p class="dashboard-info-pill dash-grey"><b>👤 Prenom  : </b><%= @user.first_name %></p>
      <div class="b-margin-20"></div>
      <p class="dashboard-info-pill dash-grey"><b>🚻 Genre  : </b><%= @user.gender %></p>
      <div class="b-margin-20"></div>
      <p class="dashboard-info-pill dash-grey"><b>🐣 Age  : </b><%= Time.now.year - @user.birthdate.year %> ans</p>
      <div class="b-margin-20"></div>
      <p class="dashboard-info-pill dash-grey"><b>📍 Ville  : </b><%= @user.city %></p>
    </div>
    <!-- This div contains the form to modify the user info (and send the new entry to the DB)-->
    <div class="user-form d-none ">
      <div class="b-margin-40"></div>
      <div class="content-center">
        <%= simple_form_for @user, url: update_users_path do |f| %>
          <%= f.input :last_name, label: 'Nom' %>
          <%= f.input :first_name, label: 'Prénom' %>
          <%= f.input :gender, label: 'Genre' %>
          <%= f.input :birthdate, label: 'Date de naissance' %>
          <%= f.input :city, label: 'Ville' %>
          <%= f.input :photo, as: :file %>
          <%= f.button :submit, "Modifier", class: "dashboard-info-pill pill-jaune ml-4" %>
        </div>
      </div>
      <!-- This div is the button to display the form and hidde the user info (and can be use to toggle)-->
      <div class="b-margin-20"></div>
      <div class= "user-info-btn dashboard-info-pill pill-jaune", remote="true">Modifier mes informations</div>
    <% end %>
    <!-- link_to destroy ? -->
    <div class="b-margin-40"></div>
  </div>
  <!------------------------------------------------------------------------>
  <!--  If the user just visit another profile, display some information. -->
  <!------------------------------------------------------------------------>
<% else %>
  <div class="content">
    <div class="offer-content">
      <%= render "shared/recrutorcard"%>
      <div class="b-margin-20"></div>
      <p class="xlarge-info-pill"><%= @profile_user.description %></p>
      <div class="b-margin-20"></div>
      <a href="mailto:moderation@jobble.fun ?subject=🤬 Signalement à propos de l'utilisateur <%=@profile_user.first_name%> <%=@profile_user.last_name%> &body=Bonjour j'aimerai signaler l'utilisateur <%=@profile_user.first_name%> <%=@profile_user.last_name%> ( UserID-<%=@profile_user.id%> ) pour les raisons ci-dessous: ">
        <h6 class="button-pill-large pill-orange"><b>🤬 Signaler</b></h6>
      </a>
      <%= link_to offers_path do %>
        <h6 class="button-pill-large pill-jaune"><b>↩️ retour</b></h6>
      <% end %>
    </div>
  </div>
<% end %>
<%# <%= link_to "Modifier mon mot de passe", edit_user_password_path %>

app/views/users/show.html.erb
<div class="container">
  <% if @user.id == current_user.id %>
    <h2>Mes informations</h2>
    <%= simple_form_for @user, url: update_users_user_path do |f| %>
      <%= f.input :last_name, label: 'Nom' %>
      <%= f.input :first_name, label: 'Prénom' %>
      <%= f.input :gender, label: 'Genre' %>
      <%= f.input :birthdate, label: 'Date de naissance' %>
      <%= f.input :city, label: 'Ville' %>
      <%= f.submit "Modifier" %>
    <% end %>
      <%= link_to "Mon dashboard", "#" %>
      <%# link_to destroy ?%>
    <% else %>
      <h2>Recruteur</h2>
      <p><%= @user.first_name %></p>
      <p><%= @user.last_name %></p>
      <p><%= @user.description %></p>
  <% end %>
  <%# <%= link_to "Modifier mon mot de passe", edit_user_password_path %>
</div>

app/views/users/skill_show.html.erb
<%= render "/shared/dashboardnavigationbar", pathname: "Mes compétences" %>
<div class="content-long-dashboard dashboard text-center">
  <div class="b-margin-30"></div>
  <% if @job_skill.count.positive? %>
    <h4>Mes compétences</h4>
    <div class="b-margin-20"></div>
    <% @job_skill.each do |skill| %>
      <% nbtimes = UserSkill.find_by_skill_id(skill.skill_id).level%>
      <% stars = "⭐️"%>
      <p class="dashboard-pill pill-lavande d-flex justify-content-center choosen-skill" data-skill="<%= skill.skill_id %>"><b><%= Skill.find(skill.skill_id).name %><br>
          <%= stars * nbtimes.to_i %></p>
      </b>
      <%= simple_form_for @skill, url: skill_update_path, method: :post do |f| %>
        <div class="choosen-skill-form-<%= skill.skill_id %> d-none">
          <div class= form-job-content>
            <%= f.input :level, label: "Votre niveau sur 5", collection: UserSkill::LEVEL %>
            <%= hidden_field_tag :skill_id, value: skill.skill_id %>
            <%= f.submit "Modifier" %>
          </div>
        </div>
      <% end %>
    <% end %>
  <% end %>
  <div data-controller="hello">
    <%= form_with url: skill_show_path, method: :get, html: {
   data: { hello_target: 'formulaire' } } do |f| %>
      <span class="input-search-div">
        <%= f.text_field :query,
                     class: "form-control",
                     placeholder: 'chercher une compétence',
                     value: params[:query],
                     data: { hello_target: 'button', action: 'keyup->hello#update' } %>
      <% end %>
    </span>
    <%= render "list_skills", skills: @skills %>
    <div class="b-margin-40"></div>
  </div>
</div>