config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'users#dashboard'
  get 'job_show', to: 'users#job_show'
  post 'job_update_test', to: 'users#job_update_test'
  get 'skill_show', to: 'users#skill_show'
  # get 'professional_update', to: 'users#professional_update'
  #  post 'job_update', to: 'users#job_update' fais la nouvelle ne sert plus
  post 'skill_update', to: 'users#skill_update'
  get 'profile', to: 'users#profile'
  get 'dashboard', to: 'users#dashboard'
  patch 'update_users', to: 'users#update_users'
  patch 'description_maj', to: 'users#description_maj'
  get 'matches', to: "offers#matches"
  get 'dashboard', to: 'users#dashboard', as: :user_root
  get 'message_index', to: 'users#message_index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :matches, only: %i[show]
  resources :users, only: %i[show]
  resources :chatrooms, only: :show do
    resources :messages, only: :create
  end

  resources :offers, only: %i[index show] do
    post 'like', to: 'matches#like'
    post 'reject', to: 'matches#reject'
  end
end

app/views/shared/_animation.html.erb
<div id="fullscreen_animation">
  <iframe src="http://localhost:3000/" style="width:10%;height:10%;"></iframe>
  <img id="animation_close" src="http://images.clipartpanda.com/happy-birthday-banner-clipart-dT6zAqaT9.png"/>
</div>

app/views/shared/_avatar.erb
<% if @user.photo.attached? && @user == current_user %>
  <div class="avatar" style= "background-image: url(<%= cl_image_path @user.photo.key, width: 200, height: 200, gravity: 'faces', crop: 'thumb' %>);">
  </div>
<% else %>
  <div class="avatar" style= "background-image: url(<%= image_path "silhouette.png"%>);">
  </div>
<% end %>

app/views/shared/_avatar_recrutor.html.erb
<div class="avatar" style="background-image: url('<%= cl_image_path Offer.find_by_title(chatroom.name).photo.key, width: 200, height: 200, gravity: 'faces', crop: 'thumb' %>');">
</div>

app/views/shared/_dashboardnavigationbar.html copy.erb
<div class="navigation-bar">
<%= link_to dashboard_path(current_user) do %>
<div><span class="fas fa-chevron-left"></span><span>dashboard</span></div>
<% end %>
<h6><%=pathname%></h6>
</div>

app/views/shared/_dashboardnavigationbar.html.erb
<div class="navigation-bar">
  <%= link_to dashboard_path(current_user) do %>
    <div><span class="fas fa-chevron-left"></span><span>dashboard</span></div>
  <% end %>
  <h6><%=pathname%></h6>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_ios_pwa_links.erb
<link rel="apple-touch-icon" sizes="57x57" href="<%= image_path 'icons/apple-icon-57x57.png' %>">
<link rel="apple-touch-icon" sizes="60x60" href="<%= image_path 'icons/apple-icon-60x60.png' %>">
<link rel="apple-touch-icon" sizes="72x72" href="<%= image_path 'icons/apple-icon-72x72.png' %>">
<link rel="apple-touch-icon" sizes="76x76" href="<%= image_path 'icons/apple-icon-76x76.png' %>">
<link rel="apple-touch-icon" sizes="114x114" href="<%= image_path 'icons/apple-icon-114x114.png' %>">
<link rel="apple-touch-icon" sizes="120x120" href="<%= image_path 'icons/apple-icon-120x120.png' %>">
<link rel="apple-touch-icon" sizes="144x144" href="<%= image_path 'icons/apple-icon-144x144.png' %>">
<link rel="apple-touch-icon" sizes="152x152" href="<%= image_path 'icons/apple-icon-152x152.png' %>">
<link rel="apple-touch-icon" sizes="180x180" href="<%= image_path 'icons/apple-icon-180x180.png' %>">
<link rel="icon" type="image/png" sizes="32x32" href="<%= image_path 'icons/favicon-32x32.png' %>">
<link rel="icon" type="image/png" sizes="96x96" href="<%= image_path 'icons/favicon-96x96.png' %>">
<link rel="icon" type="image/png" sizes="16x16" href="<%= image_path 'icons/favicon-16x16.png' %>">

app/views/shared/_messagenavigationbar.html.erb
<div class="navigation-bar">
  <%= link_to message_index_path do %>
    <div><span class="fas fa-chevron-left"></span><span> messages</span></div>
  <% end %>
  <%= link_to offer_path(Offer.find_by_title(chatroom.name)) do %>
    <h6><%=chatroom.name.first(16).downcase%></h6>
  <% end %>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to "#", class: "navbar-brand" do %>
    <%= image_tag "https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/logo.png" %>
  <% end %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item active">
          <%= link_to "Home", "#", class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Messages", "#", class: "nav-link" %>
        </li>
        <li class="nav-item dropdown">
          <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Action", "#", class: "dropdown-item" %>
            <%= link_to "Another action", "#", class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/shared/_navigationbar.html.erb
<div class="navigation-bar">
  <%= link_to :back do %>
    <div><span class="fas fa-chevron-left"></span><span> dashboard</span></div>
  <% end %>
  <h6><%=pathname%></h6>
</div>

app/views/shared/_recrutoravatar.erb
<% if @profile_user.photo.attached? %>
  <div class="avatar" style= "background-image: url(<%= cl_image_path @profile_user.photo.key, width: 200, height: 200, gravity: 'faces', crop: 'thumb' %>);">
  </div>
<% else %>
  <div class="avatar" style= "background-image: url(<%= image_path "silhouette.png"%>);">
  </div>
<% end %>

app/views/shared/_recrutorcard.html.erb
<div class="usercard">
  <%= render "shared/recrutoravatar"%>
  <div id="usercard-text">
    <h4><%= @profile_user.first_name.first(12).capitalize %></h4>
    <h4 style="font-weight:normal;"><%= @profile_user.last_name.first(11).capitalize %></h4>
    <p><%= @profile_user.offers.first.company_name.capitalize %></p>
  </div>
</div>

app/views/shared/_tabbar.html.erb
<% message_count = 0 %>
<%chatrooms = Chatroom.where(user_id: current_user.id)%>
<% chatrooms.each do |chatroom| %>
  <% if chatroom.messages %>
    <% chatroom.messages.each do |message|%>
      <% unless message.user_id == current_user.id %>
        <% if message.status == false %>
          <% message_count += 1 %>
        <% end %>
      <% end %>
    <% end %>
  <%end%>
<%end%>
<!------------------>
<nav class="tabbar anim-js-div">
  <%= link_to dashboard_path(@user), class: controller_name == "users" && action_name == "dashboard"? "tabbar-active tabbar-icons" : "tabbar-icons" do %>
    <%= render '/shared/svg/dashboard.svg' %>
    <p>Mon Profil</p>
  <% end %>
  <%= link_to offers_path, class: controller_name == "offers" && action_name == "index"? "tabbar-active tabbar-icons" : "tabbar-icons" do %>
    <%= render '/shared/svg/matchs.svg' %>
    <p>Swipez!</p>
  <% end %>
  <%= link_to message_index_path, class: (controller_name == "messages" && action_name == "create" || controller_name == "users" && action_name == "message_index") || (controller_name == "chatrooms" && action_name == "show") ? "tabbar-active tabbar-icons" : "tabbar-icons", id: "relative-notif" do %>
    <div id='message-notif' class="d-none" data-message="<%= message_count %>"></div>
    <%= render '/shared/svg/messages.svg' %>
    <p>Messages</p>
  <% end %>
</nav>

app/views/shared/_usercard.erb
<div class="usercard">
  <%= render "shared/avatar"%>
  <div id="usercard-text">
    <%= link_to destroy_user_session_path, method: :delete, class: "logout-pill dash-orange" do%>
      <p>Deconnexion</p>
    <% end %>
    <div class="b-margin-15"></div>
    <h4><%= @user.first_name.first(12).capitalize %></h4>
    <h4 style="font-weight:normal;"><%= @user.last_name.first(11).capitalize %></h4>
  </div>
</div>