config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'users#dashboard'
  get 'job_show', to: 'users#job_show'
  post 'job_update_test', to: 'users#job_update_test'
  get 'skill_show', to: 'users#skill_show'
  # get 'professional_update', to: 'users#professional_update'
  #  post 'job_update', to: 'users#job_update' fais la nouvelle ne sert plus
  post 'skill_update', to: 'users#skill_update'
  get 'profile', to: 'users#profile'
  get 'dashboard', to: 'users#dashboard'
  patch 'update_users', to: 'users#update_users'
  patch 'description_maj', to: 'users#description_maj'
  get 'matches', to: "offers#matches"
  get 'dashboard', to: 'users#dashboard', as: :user_root
  get 'message_index', to: 'users#message_index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :matches, only: %i[show]
  resources :users, only: %i[show]
  resources :chatrooms, only: :show do
    resources :messages, only: :create
  end

  resources :offers, only: %i[index show] do
    post 'like', to: 'matches#like'
    post 'reject', to: 'matches#reject'
  end
end

app/models/offer.rb
class Offer < ApplicationRecord
  belongs_to :job
  belongs_to :user
  has_many :matches, dependent: :destroy
  has_many :offer_skills, dependent: :destroy
  has_one_attached :photo

  validates :title, presence: true, length: { maximum: 35 }
  validates :description, presence: true, length: { in: 20..1200 }
  validates :location, presence: true
  validates :salary, presence: true
end

app/controllers/offers_controller.rb
class OffersController < ApplicationController
  def index
    @user = current_user
    @offers = Offer.where(job_id: @user.jobs.ids)
    @selected_offers = []
    @offers.each do |offer| # iterate through offers
      if offer.matches.count.positive? # check if offer.matches exist
        if offer.matches.find_by_user_id(@user.id).present? # if match belongs to the current user
          if offer.matches.find_by_user_id(@user.id).candidate_status.nil? # if candidate.status exist and is nil
            @selected_offers << offer
          end
        else
          @selected_offers << offer
        end
      else
        @selected_offers << offer
      end
    end
  end

  def show
    @offer = Offer.find(params[:id])
  end

  def matches
    @user = current_user
    @matches = Match.where(candidate_status: true, recrutor_status: true, user_id: @user.id)
    @offers = []
    @matches.each do |match|
      @offers << Offer.find(match.offer_id)
    end
  end
end

app/views/offers/index.html.erb
<div class="offre-js">
  <% if @selected_offers.count.positive? %>
    <div class="content-offers offers" style="max-width: 428px">
      <div class="refus-anim d-none" >
        <i class="fas fa-thumbs-down"></i>
      </div>
      <div>
        <% offer = @selected_offers.first %>
        <div>
          <style>
            .photo{background-image:url('<%= cl_image_path offer.photo.key, width: 408, height: 650 %>');}
          </style>
          <div class="photo offer-image" data-id=<%= offer.id %>></div>
          <div class="offer-global-content">
            <div class="offer-name mr-3">
              <h2><%= offer.title.capitalize %></h2>
              <h5><%= offer.company_name.capitalize %></h5>
            </div>
            <div class="offers-content">
              <div class="offer-info-content">
                <p class="info-pill">📍 <%= offer.location %></p>
                <p class="info-pill">💰 <%= (offer.salary) %>€</p>
                <p class="info-pill">🕦 <%= offer.number_hour %>h</p>
                <p class="info-pill"><%= offer.contract_type %></p>
              </div>
              <div class="offer-buttons-content">
                <%# <% if offer rejected, offer transferred filtered out of index %>
                <%= link_to "#", remote: true, id: "reject-btn" do %>
                  <h6 class="button-pill-narrow pill-indigo refus-annim-button"><b>❌ Non</b></h6>
                <% end %>
                <%# <% if match saved, offer filtered out of index and transferred to matches view avec index (link) %>
                <%= link_to "#", remote: true, id: "accept-btn" do %>
                  <h6 class="button-pill-narrow pill-jaune"><b>Like</b></h6>
                <% end %>
              </div>
              <div class="b-margin-20"></div>
              <%= link_to profile_path(offer.user.id) do  %>
                <h5><%= offer.user.first_name.capitalize %> <%= offer.user.last_name.capitalize %></h5>
                <p>Recruteur</p>
              <% end %>
              <div class="b-margin-30"></div>
              <p><%= offer.description.first(150) %>...</p>
              <div class="b-margin-30"></div>
              <%= link_to offer_path(offer) do %>
                <h6 class="button-pill-xlarge pill-indigo"><b>🧐 Decouvrir</b></h6>
              <% end %>
            </div>
          </div>
        </div>
      <% else %>
        <div class="content-long dashboard" style="max-width: 428px; margin: 0;">
          <div class="nothingfound">
            <span class="d-flex justify-content-center" style="font-size: 100px;">😥</span>
            <h5 style="text-align: center;">Aucune nouvelle offre<br>
              ne correspond à<br>
              votre profil.</h5>
          </div>
        </div>
      <% end %>
    </div>
  </div>
  <div class="modal-shadow modal-hidden">
    <div class="match-modal">
    </div>
  </div>
</div>

app/views/offers/matches.html.erb
<%= render '/shared/dashboardnavigationbar', pathname: 'Mes matches'%>
<div class="content-long-dashboard dashboard">
  <% if @offers.count.positive? %>
    <h2 class="mt-3">Mes matches</h2>
    <% @offers.each do |offer| %>
      <%= link_to offer_path(offer), class: "message-card pill-lavande" do %>
        <div class="max-length">
          <h4><%= offer.title.capitalize %></h4>
          <p><%= offer.company_name.capitalize %></p>
          <p><%= offer.user.first_name.capitalize %> <%= offer.user.last_name.capitalize %></p>
        </div>
      <% end %>
    <% end %>
  <% else %>
    <div class="nothingfound">
      <span class="d-flex justify-content-center" style="font-size: 100px;">💔</span>
      <h5 style="text-align: center;">Vous n'avez pas<br>
        encore de<br>
        matchs.</h5>
    </div>
  <% end %>
</div>

app/views/offers/show.html.erb
<div class="content-long">
  <div class="offer-content">
    <div>
      <div class="b-margin-20"></div>
      <h3><%= @offer.title.capitalize %></h3>
      <h3>💼</h3>
      <h5><%= @offer.company_name.capitalize %></h5>
      <p><%= @offer.user.first_name.capitalize %> <%= @offer.user.last_name.capitalize %></p>
      <div class="b-margin-20"></div>
      <p><%= @offer.description %></p>
    </div>
    <div class="b-margin-30"></div>
    <div>
      <p class="large-info-pill">📍 Lieu d'exécution : <b><%= @offer.location %></b></p>
      <div class="b-margin-10"></div>
      <p class="large-info-pill">💰 Salaire mensuel net : <b><%=@offer.salary%>€</b></p>
      <div class="b-margin-10"></div>
      <p class="large-info-pill">🕦 Temps de travail : <b><%= @offer.number_hour %> heures</b></p>
      <div class="b-margin-10"></div>
      <p class="large-info-pill">📝 Type de contrat : <b><%=@offer.contract_type %></b></p>
      <div class="b-margin-10"></div>
      <p class="large-info-pill">👔 Statut juridique : <b><%=@offer.employement_type.capitalize %></b></p>
    </div>
    <div class="b-margin-20"></div>
    <%= link_to :back do %>
      <h6 class="button-pill-large pill-jaune"><b>↩️ retour</b></h6>
    <% end %>
  </div>
</div>